import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  TopNavbar,
  TopNavbarChildren,
  TopNavbarItem,
  TopNavbarList,
  TopNavbarTitle,
} from "../components/top-navbar";
import { ThemeToggler } from "../components/theme-toggler";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

const navList = [
  {
    label: "Documentation",
    url: "/iframe.html",
  },
  {
    label: "Components",
    url: "/components",
  },
  {
    label: "Examples",
    url: "/examples",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNavbar>
          <TopNavbarTitle>SIGMA-UI</TopNavbarTitle>
          <TopNavbarList>
            {navList.map((item) => (
              <TopNavbarItem href={item.url} key={item.url}>
                {item.label}
              </TopNavbarItem>
            ))}
          </TopNavbarList>
          <TopNavbarChildren>
            <ThemeToggler />
          </TopNavbarChildren>
        </TopNavbar>
        {children}
      </body>
    </html>
  );
}
